<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Experience the difference</name>
   <tag></tag>
   <elementGuidId>2eb9b8e6-b3c5-41ac-9769-a337ea0b64c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topPanel']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.caption</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Experience the difference&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9e13ece6-d1e3-40ff-85ad-5784145e4f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caption</value>
      <webElementGuid>cfe75d29-4240-4615-b051-9b5bca369122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Experience the difference</value>
      <webElementGuid>47753cbc-028d-4db4-ab95-f3a8f4f9cff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topPanel&quot;)/p[@class=&quot;caption&quot;]</value>
      <webElementGuid>3c3790bc-da9f-44da-acee-9ab5dcd09448</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topPanel']/p</value>
      <webElementGuid>46479015-f71e-4115-87cf-5112ceb2ace3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solutions'])[1]/preceding::p[1]</value>
      <webElementGuid>81f8a0c0-12f7-4c26-80e1-a1a03af2fce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::p[1]</value>
      <webElementGuid>1bd52611-91f5-4cb2-a1b9-3e9c5228ff1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Experience the difference']/parent::*</value>
      <webElementGuid>db24d39c-6b65-4dd3-9725-28297c05e708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>11181b05-de0d-48b9-816b-1e11dce3ebee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Experience the difference' or . = 'Experience the difference')]</value>
      <webElementGuid>c55e5903-4d9b-4361-ba08-9bebeb7ee301</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
