<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_logout</name>
   <tag></tag>
   <elementGuidId>a8f4c654-67b3-442c-a5dd-847b71d23b70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>a[href='logout.htm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>a[href='logout.htm']</value>
      <webElementGuid>6fa91416-0647-4e54-bbc0-9053b2c13144</webElementGuid>
   </webElementProperties>
</WebElementEntity>
